spring:
  application:
    name: store
  devtools:
    restart:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/store
    username: shema
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update

stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 1000
  supported-currencies: USD,EUR,GBP
payment-gateway: stripe

